/**
  * \file gen_opcode.c
  * \author Dong Wei
  *
  * This is seperate program, which generate four files from
  * the virtual machine instruction set definition file opcode.def.
  * The generated files are:
  *     opcode.h
  *     opcode.c
  *     opcode.inc
  *     opcode.p
  */

#include <stdio.h>

int main ()
{
	FILE *fin, *fout1, *fout2, *fout3, *fout4;
	char buf[32];
	int i = 0;
	fin = fopen("opcode.def", "r");
	fout1 = fopen("opcode.h", "w");
	fout2 = fopen("opcode.c", "w");
	fout3 = fopen("opcode.inc", "w");
	fout4 = fopen("opcode.p", "w");
	fprintf(fout1, "/* filename: opcode.h\n"
			"   Definition of opcode of the virtual machine.\n"
		 	"   Generated by gen_opcode, DO NOT touch it. */\n"
			"#ifndef __PASCAL_OPCODE__\n"
			"#define __PASCAL_OPCODE__\n\n");
	fprintf(fout2, "/* filename: opcode.c\n"
			"   Generated by gen_opcode, DO NOT touch it. */\n"
			"char *opcode_symbol[] = {");
	fprintf(fout3, "/* filename: opcode.inc\n"
			"   Generated by gen_opcode, DO NOT touch it. */\n"
			"static func_t gen_code[] = {");
	for (;;)
	{
		if (fscanf(fin, "%8s", buf) != 1) break;
		if (strlen(buf) >= 8)
		{
			fprintf(stderr, "Opcode too long!\n");
			exit(-1);
		}
		fprintf(fout1, "#define OP_%s\t%d\n", buf, i);
		fprintf(fout4, "static void gen%s ()\n{\n}\n\n", buf);
		if (i == 0)
		{
			fprintf(fout2, "\"%s\"", buf);
			fprintf(fout3, "gen%s\n", buf);
		}
		else
		{
			fprintf(fout2, ",\n\t\"%s\"", buf);
			fprintf(fout3, ",gen%s\n", buf);
		}
		i++;
	}
	fprintf(fout1, "extern char *opcode_symbol[];\n");
	fprintf(fout1, "extern int op_max;\n");
	fprintf(fout1, "#endif\n");
	fprintf(fout2, "};\n");
	fprintf(fout2, "int op_max = %d;\n", i);
	fprintf(fout3, "};\n");
	fclose(fin);
	fclose(fout1);
	fclose(fout2);
	fclose(fout3);
	fclose(fout4);
}

