#ifndef __ARGUS_SERVICE__
#define __ARGUS_SERVICE__

#define ARGUS_PORT		1234

#define ARGUS_SERVICE_NULL		0
#define ARGUS_SERVICE_CREATE_STREAM	1
#define ARGUS_SERVICE_DROP_STREAM	2
#define ARGUS_SERVICE_CREATE_QUERY	3
#define ARGUS_SERVICE_DROP_QUERY	4
#define ARGUS_SERVICE_SEND_TUPLE	5

#define ARGUS_REPLY_NULL		10
#define ARGUS_REPLY_STREAM_CREATED	11
#define ARGUS_REPLY_STREAM_DROPPED	12
#define ARGUS_REPLY_QUERY_CREATED	13
#define ARGUS_REPLY_QUERY_DROPPED	14
#define ARGUS_REPLY_SEND_TUPLE		15
#define ARGUS_REPLY_ERROR			16
#endif

